/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * servidor.java
 *
 * Created on 23/04/2009, 04:46:11 PM
 */

package capaInterfaz;


import MotorLogico.serverConns;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


/**
 *
 * @author RanVLi
 */
public class servidor extends javax.swing.JFrame {

    File mapaCagado;

    final JFileChooser fc = new JFileChooser();

    capaDatos.AdmDatos capaDatos = new capaDatos.AdmDatos();

 
    public servidor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Inicia Servidor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar mapa a utilizar en servidor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       Juego_Cliente jC = new Juego_Cliente();
       jC.setVisible(true);

//       clientePrueba cp2 = new clientePrueba();
//       cp2.setVisible(true);

       newServ();

       

        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        

    int returnVal = fc.showOpenDialog(this);

    String topten[][] = null;

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            boolean compat = capaDatos.chequeaCompatibilidad(file.toString());
            if(!compat){
                JOptionPane.showMessageDialog(rootPane, "Archivo no es compatible con ExploraMundos v1.0");
                return;
            }
            //TituloRecords1.setText("Los mejores puntajes del mundo " + file.getName());
            topten = capaDatos.cargaTops(file.getPath());
            if (topten[0][0].equals("fnf")){
                JOptionPane.showMessageDialog(rootPane, "Archivo de toptens no se encuentra, creando uno en blanco.");
                String topNF[][] = { {"","0"}, {"","0"}, {"","0"}, {"","0"}, {"","0"}, {"","0"}, {"","0"}, {"","0"} ,{"","0"}, {"","0"} };
                topten = topNF;
                capaDatos.salvaTops(file.toString(), topNF);
            }
            if (topten == null){
                mapaCagado = null;
                JOptionPane.showMessageDialog(rootPane, "Error abriendo archivo de mapa.");
                return;
            }
            mapaCagado = file;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Apertura cancelada.");
            mapaCagado = null;
            //mJugar.setEnabled(false);
            return;
            //cancelado
        }


    //cargaRecords(topten);


    //mJugar.setEnabled(true);


    }//GEN-LAST:event_jButton2ActionPerformed

    public void newServ(){
        new serverConns(this, mapaCagado);

    }
    public void msg(String msg){
        
        jTextArea1.append(msg+"\n");
        
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new servidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
